# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App

  # Major pods
  pod 'R.swift'
  pod 'JTAppleCalendar'
  pod 'XJYChart', '2.5.0'
  pod "NumericPicker"
  pod 'DHSmartScreenshot', '1.3.1'

  # MS Apps related Pods
  pod 'AppCenter'
  pod 'AppCenter/Distribute'

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppUITests' do
    # Pods for testing
  end

end
